-- Criação da tabela CLIENTES
CREATE TABLE CLIENTES (
    ID INTEGER PRIMARY KEY,
    NOME TEXT,
    EMAIL TEXT
);

-- Criação da tabela FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
    ID INTEGER PRIMARY KEY,
    NOME TEXT,
    CARGO TEXT
);

-- Criação da tabela VENDAS
CREATE TABLE VENDAS (
    ID INTEGER PRIMARY KEY,
    CLIENTE_ID INTEGER,
    FUNCIONARIO_ID INTEGER,
    VALOR REAL,
    DATA_VENDA TEXT,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(ID)
);
